const error = require("../middleware/error");
const auth = require("../api/common/auth");
const categoria = require("../api/ecommerce/categoria");
const producto = require("../api/ecommerce/producto");
const fotos = require("../api/ecommerce/fotos");
const talla = require("../api/admin/talla");
const descuento = require("../api/ecommerce/descuento");
const ordenCompra = require("../api/ecommerce/ordenCompra");
const userShop = require("../api/ecommerce/userShop");
const nubefact = require("../api/ecommerce/nubefact");
const pagina = require("../api/ecommerce/pagina");
const usuario = require("../api/admin/usuario");
const productoInv = require("../api/ecommerce/productoInv");
const ordenExcel = require("../api/ecommerce/ordenExcel");
const reclamo = require("../api/ecommerce/reclamo");
const tarifas = require("../api/ecommerce/tarifas");

module.exports = function (app) {
  app.use("/tarifas", tarifas);
  app.use("/reclamo", reclamo);
  app.use("/orden-excel", ordenExcel);
  app.use("/producto-inv", productoInv);
  app.use("/usuario", usuario);
  app.use("/pagina", pagina);
  app.use("/nubefact", nubefact);
  app.use("/user-shop", userShop);
  app.use("/orden", ordenCompra);
  app.use("/descuento", descuento);
  app.use("/talla", talla);
  app.use("/fotos", fotos);
  app.use("/producto", producto);
  app.use("/categoria", categoria);
  app.use("/auth", auth);
  app.use(error);
};
