const NOT_VALID = "NOT-VALID";
const ATR_MISSED = "ATR_MISSED";
const EMPTY = "EMPTY";
const SUCCESS = "SUCCESS";
const AWS_BUCKET_NAME = "lancaster-aws";
const AWS_BUCKET_REGION = "us-east-1";
const AWS_PUBLIC_KEY = "AKIA5WMM7HJLKFGCGK2P";
const AWS_SECRET_KEY = "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";

exports.NOT_VALID = NOT_VALID;
exports.ATR_MISSED = ATR_MISSED;
exports.EMPTY = EMPTY;
exports.SUCCESS = SUCCESS;
exports.AWS_BUCKET_NAME = AWS_BUCKET_NAME;
exports.AWS_BUCKET_REGION = AWS_BUCKET_REGION;
exports.AWS_PUBLIC_KEY = AWS_PUBLIC_KEY;
exports.AWS_SECRET_KEY = AWS_SECRET_KEY;
