const NOT_VALID = "NOT-VALID";
const ATR_MISSED = "ATR_MISSED";
const EMPTY = "EMPTY";
const SUCCESS = "SUCCESS";

exports.NOT_VALID = NOT_VALID;
exports.ATR_MISSED = ATR_MISSED;
exports.EMPTY = EMPTY;
exports.SUCCESS = SUCCESS;
